{{{header(hello world,
Richard Westhaver,
ellis@rwest.io)}}}

My name is Richard. I'm a 29yo, US-based computer programmer and today
marks the birth of my first company: /The Compiler Company/.


* The Compiler Company
I intend for /The Compiler Company/ to be a hub for developing various
interconnected products and services based on cutting-edge software
and research.

I'm the sole owner and operator and will probably keep it that way for
quite some time. My intention is to operate at minimal cost while I
build prototypes.

** Software

The software provided by /The Compiler Company/ is a powerful but
opinionated programming environment. It consists of a GNU/Linux
kernel, some vendored programs and libraries, and a suite of custom
software.

The software is modular by design. You can pick and choose which
components to embed in your own projects and you are encouraged to
modify any part of the system to meet your goals. 

In general, our software is designed for:
- early adoption :: integrate research, protocols, libraries, and
  hardware features from leading research orgs faster than anyone else
- rapid development :: interaction, code introspection, tooling, and
  automation built for prototyping at massive scale
- power :: using our environment should feel like cheating - macros,
  DSLs, and unmatched hackability

*** Langs
/The Compiler Company/ is above all, a =Lisp Company=. The most
powerful software requires the most powerful code.

Lisp isn't enough though. =Rust= is our imperative language of choice
at the time of writing and generally suited for system-level software
components.

We make use of the Steel Bank Common Lisp compiler (SBCL) and the
nightly Rust compiler toolchain.

*** OS
/The Compiler Company/ is a =Linux Company=. There may be minimal
support for Darwin-based systems, but Microsoft Windows systems will
never be officially supported.

One of the /anti-goals/ of our software is ~portability~. For all of
the features we optimize for, portability becomes a burden, especially
with closed-source OS kernels. We are also explicitly driven to reduce
consumer dependence on these closed-source systems, especially in a
distributed network. They are simply unfit for use with the software
we produce.
**** TODO Windows Subsystem for Linux (WSL)
- State "TODO"       from              [2023-11-26 Sun 19:18]
* Next Steps
We have a long way to go. The important thing is to keep up the
momentum. Before the start of 2024 you can expect another update on
the projects below.
** [[https://compiler.company/docs/core][core]]
** [[https://compiler.company/docs/infra][infra]]
** [[https://compiler.company/docs/nas-t][nas-t]]
