#+TITLE: hello world
#+AUTHOR: Richard Westhaver <ellis@rwest.io>
#+OPTIONS: ^:nil toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" href="https://fonts.xz.style/serve/inter.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://packy.rwest.io/style/css/new.min.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://packy.rwest.io/style/css/terminal.css"/>
If we've spoken recently I may have mentioned this new venture I've
been working on. Now is the time to elaborate on what I've been up to,
and why.

* The Compiler Company
The name is a play on the phrase /Compiler Collection/, as in [[https://gcc.gnu.org/][GNU
Compiler Collection (GCC)]] and emphasizes my approach to
problem-solving involving compiler technologies.

I recently registered as an LLC, but the purpose of the company is
that of a company incubator, or /company compiler/ if you will. In
other words, I intend for /The Compiler Company, LLC/ to be a hub for
developing various interconnected products and services which can be
operated and managed independently of each other.

I (Richard Westhaver) am the sole owner and operator and will probably
keep it that way for quite some time. My intention is to operate at
minimal cost while I perform industry research and develop prototypes.



/The Compiler Company/ provides two things on paper:
1. free and open-source software
2. professional consulting services

The software is made publicly available without restriction and anyone
can pay for paid professional consultations/training/etc.

The /core/ of our software suite is an insanely powerful development
environment built from scratch. It is the catalyst of engineering for
every other software component I build and reflects how I believe
software should be developed /today/.

The suite further contains a mixed bag of plugins, extensions,
libraries, and applications intended for software development in
addition to /all/ vendored dependencies. This setup gives us complete
control over every possible piece of code we encounter in the systems
we operate.

* Next Steps
We have a long way to go. The important thing is to keep up the
momentum. Before the start of 2024 you can expect another update on
some of the projects below.
** the.compiler.company
** infra
** core
** nas-t
